spring.application.name=CatalogService

spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Security & Inter-service Communication
jwt.secret=super_secret_jwt_key_2024
user.service.url=http://user-service:5000
